markdown: kramdown

remote_theme: h4fan/beautiful-jekyll2

title: h4fan security
author: h4fan

keywords: "web sec,bug bounty,pen test"
gtag: G-2DJ8NB2H6M

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

