#markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.23.0"

title: h4fan security
author: h4fan

keywords: "web sec,bug bounty,pen test"
gtag: G-2DJ8NB2H6M

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

