markdown: kramdown

remote_theme: h4fan/beautiful-jekyll2

title: h4fan security
description: blog about web sec, bug bounty
author: h4fan
show_downloads: false
google_analytics: G-XVS3G74Z7P
show_discussion: true
github:
  discuss_url: https://github.com/h4fan/h4fan.github.io/discussions
url: "https://b.tcp.im"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate

google_site_verification: DiNy6sDUx_btEXz2wpFBmB5mRL0u3Ykjjb3fycp4FYU

